### ISSUE TITLE
Ticker values need to be `Scientific`

### ISSUE THREAD

**Issue by mithrandi** [tebello-thejane/bitx.hs#12]
Currently these are `Int`, which is fine for `XBTZAR` since no decimals are allowed in the price, but useless for `ETHXBT` since the prices are always fractional in this market.

**Comment by tebello-thejane** [comment]
Yes! I'm not sure why I had assumed the API would always return `Int`.

This would require, I think, a bit of a drastic change, actually. Moreover, I'm not sure I'm such a huge fan of `Scientific` anymore. But in this situation I think it might be the correct type (due to problems with floating point types).

**Comment by mithrandi** [comment]
As I understand it, the nice thing about `Scientific` is that it is cheap to decode into from JSON, and also cheap to convert to other fractional types, so you don't pay for a more expensive conversion like the one to `Rational`, unless you need it.

Regarding the API, I guess we can leave the existing function with `Int` and introduce a new one with a more appropriate type.

**Comment by tebello-thejane** [comment]
It's been a while since I looked at this, so I keep forgetting my reasoning. I had issues with `Decimal`, not `Scientific`.

Breaking the API and doing a version bump might be the most appropriate thing. This is a bug in the library, which is getting fixed, rather than a new feature. In practice, I think it will result in very easy to fix typecheck errors in user code.

**Comment by tebello-thejane** [comment]
I'll give this one a whirl.

**Comment by tebello-thejane** [comment]
Fixed: https://github.com/tebello-thejane/bitx.hs/commit/033d9c0606649553a3c1eff7a747a5f2cec7cdd2

**Comment by mithrandi** [comment]
Ooh right, I hadn't even noticed yet that orders etc. had the same problem.

**Comment by tebello-thejane** [comment]
Prices in general everywhere. Yes.

Luno's solution of putting potentially-problematic values in quotation marks and letting the consumer figure things out is actually a very good one, This way I can use Scientific to parse the values perfectly, without worrying about my JSON library inconveniently misinterpreting things for me,

**Comment by mithrandi** [comment]
Yeah, Aeson lets you parse the values directly to `Scientific`, but many other JSON libraries in other languages will just give you a `Double`, which isn't great at all.

**Comment by tebello-thejane** [comment]
More importantly, IIRC, Aeson does not like it when you give it a `Number` that's between quotation marks. Thus the whole `QuotedScientific[ mess in the code.

Anyhoo. I think it's time to push this to Hackage.
